<?php
require_once('inc/header.php');
?>
<div class="page">
    <div class="p--container">
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: 'Courier New'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: 'Courier New'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><strong><span style="font-size: 12pt; font-family: Raleway; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Mentions l&eacute;gales :</span></strong></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Donn&eacute;es personnelles</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bhind peut avoir besoin de collecter des donn&eacute;es personnelles. Par donn&eacute;es personnelles Bhind entend toutes les informations divulgu&eacute;es par les Utilisateurs - en tant que personnes physiques - quelle que soit leur nature telle que leur nom, pr&eacute;nom, e-mail, mot de passe permettant de les identifier directement ou non qu'elles soient fournies volontairement par ces derniers ou collect&eacute;es dans le cadre de leur navigation sur le Service.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les informations personnelles collect&eacute;es concernant l&rsquo;Utilisateur sont destin&eacute;es &agrave; Bhind. De telles informations peuvent &ecirc;tre copi&eacute;es, utilis&eacute;es et ou archiv&eacute;es et ne peuvent pas &ecirc;tre divulgu&eacute;es &agrave; des tiers sauf demande exig&eacute;e par la loi ou toute autorit&eacute; judiciaire.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">En application de la loi n&deg;78-17 du 6 janvier 1978 relative &agrave; l'informatique, aux fichiers et aux libert&eacute;s, chaque utilisateur dispose des droits d'opposition (article 38 de la loi), d'acc&egrave;s (articles 39, 41 et 42 de la loi) et de rectification (article 40 de la loi) des donn&eacute;es le concernant. Ainsi, il peut exiger que soient rectifi&eacute;es, compl&eacute;t&eacute;es, clarifi&eacute;es, mises &agrave; jour ou effac&eacute;es les informations le concernant qui sont inexactes, incompl&egrave;tes, &eacute;quivoques, p&eacute;rim&eacute;es, ou dont la collecte ou l'utilisation, la communication ou la conservation est interdite.</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chaque utilisateur peut exercer ces droits en &eacute;crivant &agrave; :</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bhind - 1, rue du Chablis 93000 Bobigny.</span></p>
        <p><br /><br /></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Mineurs</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Dans l'hypoth&egrave;se o&ugrave; l&rsquo;Utilisateur est une personne physique mineure, il d&eacute;clare et reconna&icirc;t avoir recueilli l'autorisation aupr&egrave;s de ses parents ou du (ou des) titulaire(s) de l'autorit&eacute; parentale le concernant pour utiliser le Service. Le (ou les) titulaire(s) de l'autorit&eacute; parentale a (ont) accept&eacute; d'&ecirc;tre garant(s) du respect de l'ensemble des dispositions des Conditions d'Utilisation lors de son Utilisation du Service.</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les parents (ou titulaires de l'autorit&eacute; parentale) sont invit&eacute;s &agrave; surveiller l'Utilisation faite par leurs enfants du Service et &agrave; garder pr&eacute;sent &agrave; l'esprit que le Service est destin&eacute; &agrave; toucher un large public et qu'en leur qualit&eacute; de tuteur l&eacute;gal, il est de la responsabilit&eacute; des parents de d&eacute;terminer quel site Web est ou non appropri&eacute; pour leur(s) enfant(s) et de surveiller l'utilisation qu'ils en font. Pour plus d&rsquo;informations sur le filtrage, notamment en vue de la protection des mineurs, Bhind recommande aux parents de se rapprocher de leur fournisseur d&rsquo;acc&egrave;s &agrave; Internet.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Loi applicable - ind&eacute;pendance des clauses</span></p>
        <p>&nbsp;</p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les Conditions d&rsquo;Utilisation seront soumises et interpr&eacute;t&eacute;es conform&eacute;ment au Droit fran&ccedil;ais. Tout litige non r&eacute;gl&eacute; de mani&egrave;re transactionnelle sera port&eacute; devant les tribunaux de Nanterre. Dans l'&eacute;ventualit&eacute; ou l'une quelconque des dispositions des Conditions d&rsquo;Utilisation serait d&eacute;clar&eacute;e nulle ou sans effet, les dispositions restantes seront consid&eacute;r&eacute;es comme applicables de plein droit.</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">La non-application ou l'absence de revendication de l'application par Bhind de l'une quelconque des dispositions des Conditions d&rsquo;Utilisation ou de l'un quelconque droit ne saurait en aucun cas &ecirc;tre interpr&eacute;t&eacute; comme une renonciation par Bhind &agrave; une telle disposition ou un tel droit, &agrave; moins que Bhind n'en convienne autrement par &eacute;crit.</span></p>
        <p>&nbsp;</p>

        <h3 style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: Raleway; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Conditions d&rsquo;utilisation</span></strong></h3>
        <h3 style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</h3>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Toute utilisation du site web distribu&eacute; par Bhind vaut acceptation des Conditions d&rsquo;Utilisation par l&rsquo;Utilisateur. Le terme &laquo; Utilisation &raquo; vise indiff&eacute;remment toute consultation, recherche ou t&eacute;l&eacute;chargement d&rsquo;&eacute;l&eacute;ment du Service. Bhind est libre de modifier &agrave; tout moment les Conditions d&rsquo;Utilisation sans notification pr&eacute;alable afin de les adapter aux &eacute;volutions du Service et des lois et r&egrave;glements en vigueur. En cons&eacute;quence, il est conseill&eacute; &agrave; tout Utilisateur d'en prendre connaissance le plus r&eacute;guli&egrave;rement possible.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Propri&eacute;t&eacute; intellectuelle</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&copy; Bhind - Tous droits de reproduction et de repr&eacute;sentation r&eacute;serv&eacute;s.</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Le contenu du Service appartient &agrave; Bhind et se trouve prot&eacute;g&eacute; par la l&eacute;gislation en vigueur sur les droits de propri&eacute;t&eacute; intellectuelle et les conventions internationales applicables. Le terme &laquo; contenu &raquo; d&eacute;signe toutes les informations pr&eacute;sentes sur le Service telles que les donn&eacute;es, textes, graphismes, images, sons, vid&eacute;os, logos, symboles, code html et dont Bhind est &eacute;diteur.</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Toute reproduction ou repr&eacute;sentation du Service, partielle ou int&eacute;grale, ou de son Contenu est soumise, dans la limite des dispositions d&rsquo;ordre public des lois et r&egrave;glements en vigueur en France, &agrave; l&rsquo;autorisation pr&eacute;alable de Bhind. Une telle autorisation reste &agrave; la discr&eacute;tion de Bhind qui n&rsquo;a pas &agrave; justifier ses d&eacute;cisions.</span></p>
        <h3 style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</h3>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Engagement des utilisateurs</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chaque Utilisateur s&rsquo;engage &agrave; faire preuve de discernement dans le cadre de la consultation qu&rsquo;il fait du Service ou des Contributions des Utilisateurs, notamment lorsqu&rsquo;il se fie &agrave; l'opportunit&eacute;, &agrave; l'utilit&eacute; ou au caract&egrave;re complet du Contenu ou des Contributions. L'Utilisateur est seul responsable de toute utilisation personnelle du Contenu ou des Contributions.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Les donn&eacute;es, d&eacute;clarations et informations fournies &agrave; Bhind par un Utilisateur lors de son inscription sont communiqu&eacute;es sous la seule responsabilit&eacute; de cet Utilisateur.</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">D'une mani&egrave;re g&eacute;n&eacute;rale, l'Utilisateur s'engage &agrave; s'abstenir de toute Utilisation malveillante destin&eacute;e &agrave; perturber ou porter atteinte au Service et/ou &agrave; Bhind, &agrave; ses partenaires, et aux programmes de Bhind et de ses partenaires.</span></p>
        <p style="line-height: 1.6285714285714286; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><br /></span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Garanties et responsabilit&eacute;s</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Le Contenu du Service est fourni "en l'&eacute;tat", sans garantie d'aucune sorte, ni expresse, ni tacite autre que celle pr&eacute;vue par la loi en vigueur, et notamment sans garantie que le Contenu r&eacute;ponde aux besoins de l'Utilisateur ni que le Contenu soit &agrave; jour.</span><span style="font-size: 10.5pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> &nbsp;&nbsp;</span></p>
        <p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 15pt; text-align: justify;"><span style="font-size: 11pt; font-family: Raleway; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bien que Bhind s'efforce de fournir un Contenu fiable sur son Service, elle ne garantit pas que son Service soit exempt d'inexactitudes, d'erreurs typographiques, d'omissions et/ou de virus. Bhind se r&eacute;serve &agrave; tout moment et sans pr&eacute;avis le droit d'apporter des am&eacute;liorations et/ou des modifications au Contenu de son Service.</span></p>
        <h3 style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><br /><br /></h3>

    </div>
</div>
<?php
require_once('inc/footer.php');